#importonce 

notePositions:{
    redKeys:{
        .byte $00  
        .byte $12  
        .byte $14  
        .byte $16  
        .byte $16  
        .byte $00  
        .byte $1d  
        .byte $1d  
        .byte $00  
        .byte $1b  
        .byte $1b  
        .byte $00  
        .byte $12  
        .byte $12  
        .byte $14  
        .byte $16  
        .byte $16  
        .byte $00  
        .byte $1d  
        .byte $1d  
        .byte $00  
        .byte $1c  
        .byte $1c  
        .byte $00  
        .byte $11  
        .byte $11  
        .byte $13  
        .byte $17  
        .byte $17  
        .byte $00  
        .byte $1e  
        .byte $1e  
        .byte $00  
        .byte $1c  
        .byte $1c  
        .byte $00  
        .byte $11  
        .byte $11  
        .byte $13  
        .byte $17  
        .byte $17  
        .byte $00  
        .byte $1e  
        .byte $1e  
        .byte $00  
        .byte $1b  
        .byte $1b  
        .byte $00  
        .byte $12  
        .byte $12  
        .byte $14  
        .byte $16  
        .byte $19  
        .byte $00  
        .byte $1f  
        .byte $1f  
        .byte $00  
        .byte $1d  
        .byte $1d  
        .byte $00  
        .byte $12  
        .byte $12  
        .byte $14  
        .byte $16  
        .byte $19  
        .byte $00  
        .byte $1f  
        .byte $1f  
        .byte $00  
        .byte $1e  
        .byte $1e  
        .byte $00  
        .byte $13  
        .byte $13  
        .byte $15  
        .byte $17  
        .byte $17  
        .byte $17  
        .byte $15  
        .byte $16  
        .byte $1b  
        .byte $1b  
        .byte $19  
        .byte $14  
        .byte $14  
        .byte $15  
        .byte $17  
        .byte $16  
        .byte $12  
        .byte $12  
        .byte $12  
        .byte $00  
        .byte $00  
        .byte $00  
        .byte $00  
        .byte $00  
        .byte $00  
        .byte $00  
        .byte $00  
        .byte $00  
    }
    blueKeys:{
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $09
        .byte $0c
        .byte $0c
        .byte $06
        .byte $0c
        .byte $0c
        .byte $09
        .byte $0c
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $0b
        .byte $0d
        .byte $0d
        .byte $06
        .byte $0d
        .byte $0d
        .byte $0b
        .byte $0d
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $0b
        .byte $0d
        .byte $0d
        .byte $06
        .byte $0d
        .byte $0d
        .byte $0b
        .byte $0d
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $09
        .byte $0c
        .byte $0c
        .byte $06
        .byte $0c
        .byte $0c
        .byte $09
        .byte $0c
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $0c
        .byte $0e
        .byte $0e
        .byte $0c
        .byte $0e
        .byte $0e
        .byte $0c
        .byte $0e
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $0d
        .byte $0f
        .byte $0f
        .byte $0d
        .byte $0f
        .byte $0f
        .byte $0d
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $0e
        .byte $10
        .byte $10
        .byte $0e
        .byte $10
        .byte $10
        .byte $09
        .byte $0c
        .byte $0c
        .byte $09
        .byte $00
        .byte $00
        .byte $0d
        .byte $0d
        .byte $09
        .byte $00
        .byte $09
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
    }
}