
// 4 sprites generated with spritemateX on 28/04/2024, 14:22:31

// sprite 0, Width : 8, Height : 8, Colour Depth : 2

PianoTile0:
.byte $fe          //  XXXXXXX.
.byte $fe          //  XXXXXXX.
.byte $fe          //  XXXXXXX.
.byte $fe          //  XXXXXXX.
.byte $fe          //  XXXXXXX.
.byte $fe          //  XXXXXXX.
.byte $fe          //  XXXXXXX.
.byte $fe          //  XXXXXXX.


// sprite 1, Width : 8, Height : 8, Colour Depth : 2

PianoTile1:
.byte $f8          //  XXXXX...
.byte $f8          //  XXXXX...
.byte $f8          //  XXXXX...
.byte $f8          //  XXXXX...
.byte $f8          //  XXXXX...
.byte $f8          //  XXXXX...
.byte $f8          //  XXXXX...
.byte $f8          //  XXXXX...


// sprite 2, Width : 8, Height : 8, Colour Depth : 2

PianoTile2:
.byte $3e          //  ..XXXXX.
.byte $3e          //  ..XXXXX.
.byte $3e          //  ..XXXXX.
.byte $3e          //  ..XXXXX.
.byte $3e          //  ..XXXXX.
.byte $3e          //  ..XXXXX.
.byte $3e          //  ..XXXXX.
.byte $3e          //  ..XXXXX.


// sprite 3, Width : 8, Height : 8, Colour Depth : 2

PianoTile3:
.byte $38          //  ..XXX...
.byte $38          //  ..XXX...
.byte $38          //  ..XXX...
.byte $38          //  ..XXX...
.byte $38          //  ..XXX...
.byte $38          //  ..XXX...
.byte $38          //  ..XXX...
.byte $38          //  ..XXX...
