
// 70 sprites generated with spritemateX on 22/04/2024, 20:14:23

// sprite 0, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile0:
.byte $ff          //  XXXXXXXX
.byte $81          //  X......X
.byte $81          //  X......X
.byte $42          //  .X....X.
.byte $3c          //  ..XXXX..
.byte $10          //  ...X....
.byte $60          //  .XX.....
.byte $60          //  .XX.....


// sprite 1, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile1:
.byte $ff          //  XXXXXXXX
.byte $81          //  X......X
.byte $81          //  X......X
.byte $42          //  .X....X.
.byte $3c          //  ..XXXX..
.byte $08          //  ....X...
.byte $06          //  .....XX.
.byte $06          //  .....XX.


// sprite 2, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile2:
.byte $00          //  ........
.byte $00          //  ........
.byte $ff          //  XXXXXXXX
.byte $ff          //  XXXXXXXX
.byte $ff          //  XXXXXXXX
.byte $ff          //  XXXXXXXX
.byte $00          //  ........
.byte $00          //  ........


// sprite 3, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile3:
.byte $00          //  ........
.byte $00          //  ........
.byte $ff          //  XXXXXXXX
.byte $ff          //  XXXXXXXX
.byte $ff          //  XXXXXXXX
.byte $ff          //  XXXXXXXX
.byte $00          //  ........
.byte $00          //  ........


// sprite 4, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile4:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........


// sprite 5, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile5:
.byte $00          //  ........
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $00          //  ........
.byte $10          //  ...X....
.byte $00          //  ........


// sprite 6, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile6:
.byte $00          //  ........
.byte $24          //  ..X..X..
.byte $24          //  ..X..X..
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........


// sprite 7, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile7:
.byte $00          //  ........
.byte $24          //  ..X..X..
.byte $7e          //  .XXXXXX.
.byte $24          //  ..X..X..
.byte $24          //  ..X..X..
.byte $7e          //  .XXXXXX.
.byte $24          //  ..X..X..
.byte $00          //  ........


// sprite 8, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile8:
.byte $00          //  ........
.byte $08          //  ....X...
.byte $1e          //  ...XXXX.
.byte $28          //  ..X.X...
.byte $1c          //  ...XXX..
.byte $0a          //  ....X.X.
.byte $3c          //  ..XXXX..
.byte $08          //  ....X...


// sprite 9, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile9:
.byte $00          //  ........
.byte $62          //  .XX...X.
.byte $64          //  .XX..X..
.byte $08          //  ....X...
.byte $10          //  ...X....
.byte $26          //  ..X..XX.
.byte $46          //  .X...XX.
.byte $00          //  ........


// sprite 10, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile10:
.byte $00          //  ........
.byte $10          //  ...X....
.byte $28          //  ..X.X...
.byte $10          //  ...X....
.byte $2a          //  ..X.X.X.
.byte $44          //  .X...X..
.byte $3a          //  ..XXX.X.
.byte $00          //  ........


// sprite 11, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile11:
.byte $00          //  ........
.byte $08          //  ....X...
.byte $10          //  ...X....
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........


// sprite 12, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile12:
.byte $00          //  ........
.byte $04          //  .....X..
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $04          //  .....X..
.byte $00          //  ........


// sprite 13, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile13:
.byte $00          //  ........
.byte $20          //  ..X.....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $20          //  ..X.....
.byte $00          //  ........


// sprite 14, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile14:
.byte $00          //  ........
.byte $00          //  ........
.byte $14          //  ...X.X..
.byte $08          //  ....X...
.byte $3e          //  ..XXXXX.
.byte $08          //  ....X...
.byte $14          //  ...X.X..
.byte $00          //  ........


// sprite 15, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile15:
.byte $00          //  ........
.byte $00          //  ........
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $3e          //  ..XXXXX.
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $00          //  ........


// sprite 16, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile16:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $10          //  ...X....


// sprite 17, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile17:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $3e          //  ..XXXXX.
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........


// sprite 18, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile18:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $18          //  ...XX...
.byte $18          //  ...XX...
.byte $00          //  ........


// sprite 19, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile19:
.byte $00          //  ........
.byte $00          //  ........
.byte $02          //  ......X.
.byte $04          //  .....X..
.byte $08          //  ....X...
.byte $10          //  ...X....
.byte $20          //  ..X.....
.byte $00          //  ........


// sprite 20, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile20:
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $46          //  .X...XX.
.byte $4a          //  .X..X.X.
.byte $52          //  .X.X..X.
.byte $62          //  .XX...X.
.byte $3c          //  ..XXXX..
.byte $00          //  ........


// sprite 21, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile21:
.byte $00          //  ........
.byte $18          //  ...XX...
.byte $28          //  ..X.X...
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $3e          //  ..XXXXX.
.byte $00          //  ........


// sprite 22, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile22:
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $42          //  .X....X.
.byte $02          //  ......X.
.byte $3c          //  ..XXXX..
.byte $40          //  .X......
.byte $7e          //  .XXXXXX.
.byte $00          //  ........


// sprite 23, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile23:
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $42          //  .X....X.
.byte $0c          //  ....XX..
.byte $02          //  ......X.
.byte $42          //  .X....X.
.byte $3c          //  ..XXXX..
.byte $00          //  ........


// sprite 24, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile24:
.byte $00          //  ........
.byte $08          //  ....X...
.byte $18          //  ...XX...
.byte $28          //  ..X.X...
.byte $48          //  .X..X...
.byte $7e          //  .XXXXXX.
.byte $08          //  ....X...
.byte $00          //  ........


// sprite 25, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile25:
.byte $00          //  ........
.byte $7e          //  .XXXXXX.
.byte $40          //  .X......
.byte $7c          //  .XXXXX..
.byte $02          //  ......X.
.byte $02          //  ......X.
.byte $7c          //  .XXXXX..
.byte $00          //  ........


// sprite 26, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile26:
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $40          //  .X......
.byte $7c          //  .XXXXX..
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $3c          //  ..XXXX..
.byte $00          //  ........


// sprite 27, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile27:
.byte $00          //  ........
.byte $7e          //  .XXXXXX.
.byte $02          //  ......X.
.byte $04          //  .....X..
.byte $08          //  ....X...
.byte $10          //  ...X....
.byte $20          //  ..X.....
.byte $00          //  ........


// sprite 28, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile28:
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $42          //  .X....X.
.byte $3c          //  ..XXXX..
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $3c          //  ..XXXX..
.byte $00          //  ........


// sprite 29, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile29:
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $3e          //  ..XXXXX.
.byte $02          //  ......X.
.byte $3c          //  ..XXXX..
.byte $00          //  ........


// sprite 30, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile30:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $10          //  ...X....
.byte $00          //  ........
.byte $00          //  ........
.byte $10          //  ...X....
.byte $00          //  ........


// sprite 31, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile31:
.byte $00          //  ........
.byte $00          //  ........
.byte $10          //  ...X....
.byte $00          //  ........
.byte $00          //  ........
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $20          //  ..X.....


// sprite 32, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile32:
.byte $00          //  ........
.byte $00          //  ........
.byte $04          //  .....X..
.byte $08          //  ....X...
.byte $10          //  ...X....
.byte $08          //  ....X...
.byte $04          //  .....X..
.byte $00          //  ........


// sprite 33, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile33:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $3e          //  ..XXXXX.
.byte $00          //  ........
.byte $3e          //  ..XXXXX.
.byte $00          //  ........
.byte $00          //  ........


// sprite 34, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile34:
.byte $00          //  ........
.byte $00          //  ........
.byte $10          //  ...X....
.byte $08          //  ....X...
.byte $04          //  .....X..
.byte $08          //  ....X...
.byte $10          //  ...X....
.byte $00          //  ........


// sprite 35, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile35:
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $42          //  .X....X.
.byte $04          //  .....X..
.byte $08          //  ....X...
.byte $00          //  ........
.byte $08          //  ....X...
.byte $00          //  ........


// sprite 36, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile36:
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $4a          //  .X..X.X.
.byte $56          //  .X.X.XX.
.byte $5e          //  .X.XXXX.
.byte $40          //  .X......
.byte $3c          //  ..XXXX..
.byte $00          //  ........


// sprite 37, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile37:
.byte $00          //  ........
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $04          //  .....X..
.byte $3c          //  ..XXXX..
.byte $44          //  .X...X..
.byte $3c          //  ..XXXX..
.byte $00          //  ........


// sprite 38, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile38:
.byte $00          //  ........
.byte $20          //  ..X.....
.byte $20          //  ..X.....
.byte $3c          //  ..XXXX..
.byte $22          //  ..X...X.
.byte $22          //  ..X...X.
.byte $3c          //  ..XXXX..
.byte $00          //  ........


// sprite 39, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile39:
.byte $00          //  ........
.byte $00          //  ........
.byte $1c          //  ...XXX..
.byte $20          //  ..X.....
.byte $20          //  ..X.....
.byte $20          //  ..X.....
.byte $1c          //  ...XXX..
.byte $00          //  ........


// sprite 40, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile40:
.byte $00          //  ........
.byte $04          //  .....X..
.byte $04          //  .....X..
.byte $3c          //  ..XXXX..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $3c          //  ..XXXX..
.byte $00          //  ........


// sprite 41, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile41:
.byte $00          //  ........
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $78          //  .XXXX...
.byte $40          //  .X......
.byte $38          //  ..XXX...
.byte $00          //  ........


// sprite 42, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile42:
.byte $00          //  ........
.byte $0c          //  ....XX..
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $18          //  ...XX...
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $00          //  ........


// sprite 43, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile43:
.byte $00          //  ........
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $3c          //  ..XXXX..
.byte $04          //  .....X..
.byte $38          //  ..XXX...


// sprite 44, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile44:
.byte $00          //  ........
.byte $40          //  .X......
.byte $40          //  .X......
.byte $78          //  .XXXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $00          //  ........


// sprite 45, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile45:
.byte $00          //  ........
.byte $10          //  ...X....
.byte $00          //  ........
.byte $30          //  ..XX....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $38          //  ..XXX...
.byte $00          //  ........


// sprite 46, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile46:
.byte $00          //  ........
.byte $04          //  .....X..
.byte $00          //  ........
.byte $04          //  .....X..
.byte $04          //  .....X..
.byte $04          //  .....X..
.byte $24          //  ..X..X..
.byte $18          //  ...XX...


// sprite 47, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile47:
.byte $00          //  ........
.byte $20          //  ..X.....
.byte $28          //  ..X.X...
.byte $30          //  ..XX....
.byte $30          //  ..XX....
.byte $28          //  ..X.X...
.byte $24          //  ..X..X..
.byte $00          //  ........


// sprite 48, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile48:
.byte $00          //  ........
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $0c          //  ....XX..
.byte $00          //  ........


// sprite 49, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile49:
.byte $00          //  ........
.byte $00          //  ........
.byte $68          //  .XX.X...
.byte $54          //  .X.X.X..
.byte $54          //  .X.X.X..
.byte $54          //  .X.X.X..
.byte $54          //  .X.X.X..
.byte $00          //  ........


// sprite 50, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile50:
.byte $00          //  ........
.byte $00          //  ........
.byte $78          //  .XXXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $00          //  ........


// sprite 51, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile51:
.byte $00          //  ........
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...
.byte $00          //  ........


// sprite 52, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile52:
.byte $00          //  ........
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $22          //  ..X...X.
.byte $22          //  ..X...X.
.byte $3c          //  ..XXXX..
.byte $20          //  ..X.....
.byte $20          //  ..X.....


// sprite 53, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile53:
.byte $00          //  ........
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $3c          //  ..XXXX..
.byte $04          //  .....X..
.byte $02          //  ......X.


// sprite 54, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile54:
.byte $00          //  ........
.byte $00          //  ........
.byte $1c          //  ...XXX..
.byte $20          //  ..X.....
.byte $20          //  ..X.....
.byte $20          //  ..X.....
.byte $20          //  ..X.....
.byte $00          //  ........


// sprite 55, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile55:
.byte $00          //  ........
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $40          //  .X......
.byte $38          //  ..XXX...
.byte $04          //  .....X..
.byte $78          //  .XXXX...
.byte $00          //  ........


// sprite 56, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile56:
.byte $00          //  ........
.byte $10          //  ...X....
.byte $38          //  ..XXX...
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $0c          //  ....XX..
.byte $00          //  ........


// sprite 57, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile57:
.byte $00          //  ........
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...
.byte $00          //  ........


// sprite 58, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile58:
.byte $00          //  ........
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $28          //  ..X.X...
.byte $28          //  ..X.X...
.byte $10          //  ...X....
.byte $00          //  ........


// sprite 59, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile59:
.byte $00          //  ........
.byte $00          //  ........
.byte $54          //  .X.X.X..
.byte $54          //  .X.X.X..
.byte $54          //  .X.X.X..
.byte $54          //  .X.X.X..
.byte $28          //  ..X.X...
.byte $00          //  ........


// sprite 60, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile60:
.byte $00          //  ........
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $28          //  ..X.X...
.byte $10          //  ...X....
.byte $28          //  ..X.X...
.byte $44          //  .X...X..
.byte $00          //  ........


// sprite 61, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile61:
.byte $00          //  ........
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $3c          //  ..XXXX..
.byte $04          //  .....X..
.byte $38          //  ..XXX...


// sprite 62, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile62:
.byte $00          //  ........
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $08          //  ....X...
.byte $10          //  ...X....
.byte $20          //  ..X.....
.byte $7c          //  .XXXXX..
.byte $00          //  ........


// sprite 63, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile63:
.byte $00          //  ........
.byte $0e          //  ....XXX.
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $0e          //  ....XXX.
.byte $00          //  ........


// sprite 64, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile64:
.byte $00          //  ........
.byte $00          //  ........
.byte $40          //  .X......
.byte $20          //  ..X.....
.byte $10          //  ...X....
.byte $08          //  ....X...
.byte $04          //  .....X..
.byte $00          //  ........


// sprite 65, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile65:
.byte $00          //  ........
.byte $70          //  .XXX....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $70          //  .XXX....
.byte $00          //  ........


// sprite 66, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile66:
.byte $00          //  ........
.byte $10          //  ...X....
.byte $38          //  ..XXX...
.byte $54          //  .X.X.X..
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $00          //  ........


// sprite 67, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile67:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $ff          //  XXXXXXXX


// sprite 68, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile68:
.byte $00          //  ........
.byte $1c          //  ...XXX..
.byte $22          //  ..X...X.
.byte $78          //  .XXXX...
.byte $20          //  ..X.....
.byte $20          //  ..X.....
.byte $7e          //  .XXXXXX.
.byte $00          //  ........


// sprite 69, Width : 8, Height : 8, Colour Depth : 2

LowerCharTile69:
.byte $ff          //  XXXXXXXX
.byte $ff          //  XXXXXXXX
.byte $ff          //  XXXXXXXX
.byte $ff          //  XXXXXXXX
.byte $ff          //  XXXXXXXX
.byte $ff          //  XXXXXXXX
.byte $ff          //  XXXXXXXX
.byte $ff          //  XXXXXXXX
