
// 31 sprites generated with spritemateX on 22/04/2024, 20:14:58

// sprite 0, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile0:
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $7e          //  .XXXXXX.
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $00          //  ........


// sprite 1, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile1:
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $42          //  .X....X.
.byte $7c          //  .XXXXX..
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $7c          //  .XXXXX..
.byte $00          //  ........


// sprite 2, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile2:
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......
.byte $3c          //  ..XXXX..
.byte $00          //  ........


// sprite 3, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile3:
.byte $00          //  ........
.byte $78          //  .XXXX...
.byte $44          //  .X...X..
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $44          //  .X...X..
.byte $78          //  .XXXX...
.byte $00          //  ........


// sprite 4, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile4:
.byte $00          //  ........
.byte $7e          //  .XXXXXX.
.byte $40          //  .X......
.byte $7c          //  .XXXXX..
.byte $40          //  .X......
.byte $40          //  .X......
.byte $7e          //  .XXXXXX.
.byte $00          //  ........


// sprite 5, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile5:
.byte $00          //  ........
.byte $7e          //  .XXXXXX.
.byte $40          //  .X......
.byte $7c          //  .XXXXX..
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......
.byte $00          //  ........


// sprite 6, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile6:
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $42          //  .X....X.
.byte $40          //  .X......
.byte $4e          //  .X..XXX.
.byte $42          //  .X....X.
.byte $3c          //  ..XXXX..
.byte $00          //  ........


// sprite 7, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile7:
.byte $00          //  ........
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $7e          //  .XXXXXX.
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $00          //  ........


// sprite 8, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile8:
.byte $00          //  ........
.byte $3e          //  ..XXXXX.
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $3e          //  ..XXXXX.
.byte $00          //  ........


// sprite 9, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile9:
.byte $00          //  ........
.byte $02          //  ......X.
.byte $02          //  ......X.
.byte $02          //  ......X.
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $3c          //  ..XXXX..
.byte $00          //  ........


// sprite 10, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile10:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $48          //  .X..X...
.byte $70          //  .XXX....
.byte $48          //  .X..X...
.byte $44          //  .X...X..
.byte $42          //  .X....X.
.byte $00          //  ........


// sprite 11, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile11:
.byte $00          //  ........
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......
.byte $7e          //  .XXXXXX.
.byte $00          //  ........


// sprite 12, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile12:
.byte $00          //  ........
.byte $42          //  .X....X.
.byte $66          //  .XX..XX.
.byte $5a          //  .X.XX.X.
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $00          //  ........


// sprite 13, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile13:
.byte $00          //  ........
.byte $42          //  .X....X.
.byte $62          //  .XX...X.
.byte $52          //  .X.X..X.
.byte $4a          //  .X..X.X.
.byte $46          //  .X...XX.
.byte $42          //  .X....X.
.byte $00          //  ........


// sprite 14, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile14:
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $3c          //  ..XXXX..
.byte $00          //  ........


// sprite 15, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile15:
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $7c          //  .XXXXX..
.byte $40          //  .X......
.byte $40          //  .X......
.byte $00          //  ........


// sprite 16, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile16:
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $52          //  .X.X..X.
.byte $4a          //  .X..X.X.
.byte $3c          //  ..XXXX..
.byte $00          //  ........


// sprite 17, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile17:
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $7c          //  .XXXXX..
.byte $44          //  .X...X..
.byte $42          //  .X....X.
.byte $00          //  ........


// sprite 18, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile18:
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $40          //  .X......
.byte $3c          //  ..XXXX..
.byte $02          //  ......X.
.byte $42          //  .X....X.
.byte $3c          //  ..XXXX..
.byte $00          //  ........


// sprite 19, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile19:
.byte $00          //  ........
.byte $fe          //  XXXXXXX.
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $00          //  ........


// sprite 20, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile20:
.byte $00          //  ........
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $3c          //  ..XXXX..
.byte $00          //  ........


// sprite 21, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile21:
.byte $00          //  ........
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $24          //  ..X..X..
.byte $18          //  ...XX...
.byte $00          //  ........


// sprite 22, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile22:
.byte $00          //  ........
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $42          //  .X....X.
.byte $5a          //  .X.XX.X.
.byte $24          //  ..X..X..
.byte $00          //  ........


// sprite 23, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile23:
.byte $00          //  ........
.byte $42          //  .X....X.
.byte $24          //  ..X..X..
.byte $18          //  ...XX...
.byte $18          //  ...XX...
.byte $24          //  ..X..X..
.byte $42          //  .X....X.
.byte $00          //  ........


// sprite 24, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile24:
.byte $00          //  ........
.byte $82          //  X.....X.
.byte $44          //  .X...X..
.byte $28          //  ..X.X...
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $00          //  ........


// sprite 25, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile25:
.byte $00          //  ........
.byte $7e          //  .XXXXXX.
.byte $04          //  .....X..
.byte $08          //  ....X...
.byte $10          //  ...X....
.byte $20          //  ..X.....
.byte $7e          //  .XXXXXX.
.byte $00          //  ........


// sprite 26, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile26:
.byte $00          //  ........
.byte $06          //  .....XX.
.byte $08          //  ....X...
.byte $30          //  ..XX....
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $06          //  .....XX.
.byte $00          //  ........


// sprite 27, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile27:
.byte $00          //  ........
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $00          //  ........


// sprite 28, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile28:
.byte $00          //  ........
.byte $60          //  .XX.....
.byte $10          //  ...X....
.byte $0c          //  ....XX..
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $60          //  .XX.....
.byte $00          //  ........


// sprite 29, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile29:
.byte $00          //  ........
.byte $14          //  ...X.X..
.byte $28          //  ..X.X...
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........


// sprite 30, Width : 8, Height : 8, Colour Depth : 2

UpperCharTile30:
.byte $3c          //  ..XXXX..
.byte $42          //  .X....X.
.byte $99          //  X..XX..X
.byte $a1          //  X.X....X
.byte $a1          //  X.X....X
.byte $99          //  X..XX..X
.byte $42          //  .X....X.
.byte $3c          //  ..XXXX..
